spring:
  ### Console ###
  output:
    ansi:
      enabled: always

  ### Database ###
  datasource:
    url: jdbc:h2:tcp://localhost/~/multiModule
    driver-class-name: org.h2.Driver
    username: sa

  ### JPA ###
  jpa:
    hibernate:
      ddl-auto: create #validate
    properties:
      hibernate:
        default_batch_fetch_size : 1000
        #        show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace